#!/usr/bin/env bash
set -euo pipefail

# Repack the NVIDIA VPI debian packages into the conda prefix.
#
# The shipped libnvvpi.so.* is installed byte-for-byte unmodified. We only add
# packaging glue: a relocatable CMake package config, because NVIDIA's generated
# one resolves its prefix by walking four directories up from
# lib/x86_64-linux-gnu/cmake/vpi/, which does not match a conda layout.

DEB_ROOT="${SRC_DIR}/deb"
mkdir -p "${DEB_ROOT}"

# bsdtar reads the outer `ar` container, then the inner data.tar.xz from stdin.
for deb in libnvvpi4 vpi4-dev; do
  bsdtar -xOf "${SRC_DIR}/${deb}.deb" data.tar.xz | bsdtar -xf - -C "${DEB_ROOT}"
done

VPI="${DEB_ROOT}/opt/nvidia/vpi4"
LIBDIR="${VPI}/lib/x86_64-linux-gnu"

# --- runtime + dev libraries ------------------------------------------------
mkdir -p "${PREFIX}/lib"
# -a preserves the libnvvpi.so.4 -> libnvvpi.so.4.0.5 symlink and the mode bits.
cp -a "${LIBDIR}/libnvvpi.so.${PKG_VERSION}" "${PREFIX}/lib/"
cp -a "${LIBDIR}/libnvvpi.so.4"              "${PREFIX}/lib/"
cp -a "${LIBDIR}/libnvvpi.so"                "${PREFIX}/lib/"

# --- headers ----------------------------------------------------------------
mkdir -p "${PREFIX}/include"
cp -a "${VPI}/include/vpi" "${PREFIX}/include/"

# --- CMake package config ---------------------------------------------------
# Written here rather than reused from the deb, so that the prefix is resolved
# relative to this file and the package stays relocatable.
CMAKEDIR="${PREFIX}/lib/cmake/vpi"
mkdir -p "${CMAKEDIR}"

cat > "${CMAKEDIR}/vpi-config.cmake" <<EOF
# CMake package configuration for NVIDIA VPI, generated by the conda recipe.
#
# Provides the imported target \`vpi\` (and the namespaced alias \`vpi::vpi\`),
# matching the target name that NVIDIA's own vpi-config.cmake exports and that
# isaac_ros_common / isaac_ros_nitros link against.

get_filename_component(_vpi_prefix "\${CMAKE_CURRENT_LIST_DIR}/../../.." REALPATH)

set(VPI_VERSION "${PKG_VERSION}")
set(VPI_INCLUDE_DIR  "\${_vpi_prefix}/include")
set(VPI_INCLUDE_DIRS "\${VPI_INCLUDE_DIR}")
set(VPI_LIBRARY      "\${_vpi_prefix}/lib/libnvvpi.so.${PKG_VERSION}")
set(VPI_LIBRARIES    vpi)

if(NOT TARGET vpi)
  add_library(vpi SHARED IMPORTED)
  set_target_properties(vpi PROPERTIES
    IMPORTED_LOCATION "\${VPI_LIBRARY}"
    IMPORTED_SONAME "libnvvpi.so.4"
    INTERFACE_INCLUDE_DIRECTORIES "\${VPI_INCLUDE_DIR}")
endif()

if(NOT TARGET vpi::vpi)
  add_library(vpi::vpi ALIAS vpi)
endif()

unset(_vpi_prefix)
EOF

cat > "${CMAKEDIR}/vpi-config-version.cmake" <<EOF
set(PACKAGE_VERSION "${PKG_VERSION}")

# VPI follows the usual "compatible within the same major version" rule.
if(PACKAGE_FIND_VERSION VERSION_GREATER PACKAGE_VERSION)
  set(PACKAGE_VERSION_COMPATIBLE FALSE)
else()
  string(REGEX MATCH "^[0-9]+" _vpi_have_major "\${PACKAGE_VERSION}")
  string(REGEX MATCH "^[0-9]+" _vpi_want_major "\${PACKAGE_FIND_VERSION}")
  if(PACKAGE_FIND_VERSION STREQUAL "" OR _vpi_have_major STREQUAL _vpi_want_major)
    set(PACKAGE_VERSION_COMPATIBLE TRUE)
    if(PACKAGE_FIND_VERSION STREQUAL PACKAGE_VERSION)
      set(PACKAGE_VERSION_EXACT TRUE)
    endif()
  else()
    set(PACKAGE_VERSION_COMPATIBLE FALSE)
  endif()
  unset(_vpi_have_major)
  unset(_vpi_want_major)
endif()
EOF

# --- runtime library search path --------------------------------------------
# libnvvpi dlopen's its CUDA backends (libnppc, libcufft, libcudart, libcuda) by
# bare soname. Its own RUNPATH still points at /opt/nvidia/vpi4/..., which we
# deliberately do not rewrite, so dlopen would not find them inside a conda
# prefix. Rather than patch NVIDIA's binary, put $PREFIX/lib on the loader path
# at environment-activation time.
for sh in activate deactivate; do
  mkdir -p "${PREFIX}/etc/conda/${sh}.d"
done

cat > "${PREFIX}/etc/conda/activate.d/vpi-activate.sh" <<'EOF'
# VPI resolves its CUDA backends with dlopen() by bare soname, and its RUNPATH
# points outside the conda prefix. Make $CONDA_PREFIX/lib discoverable.
export VPI_CONDA_LD_LIBRARY_PATH_BACKUP="${LD_LIBRARY_PATH:-}"
if [ -n "${LD_LIBRARY_PATH:-}" ]; then
  export LD_LIBRARY_PATH="${CONDA_PREFIX}/lib:${LD_LIBRARY_PATH}"
else
  export LD_LIBRARY_PATH="${CONDA_PREFIX}/lib"
fi
EOF

cat > "${PREFIX}/etc/conda/deactivate.d/vpi-deactivate.sh" <<'EOF'
if [ -n "${VPI_CONDA_LD_LIBRARY_PATH_BACKUP+x}" ]; then
  if [ -z "${VPI_CONDA_LD_LIBRARY_PATH_BACKUP}" ]; then
    unset LD_LIBRARY_PATH
  else
    export LD_LIBRARY_PATH="${VPI_CONDA_LD_LIBRARY_PATH_BACKUP}"
  fi
  unset VPI_CONDA_LD_LIBRARY_PATH_BACKUP
fi
EOF

# --- licenses ---------------------------------------------------------------
# Staged into the recipe work dir; the recipe's `license_file` picks them up.
cp "${VPI}/doc/VPI_EULA.txt" "${SRC_DIR}/VPI_EULA.txt"
mkdir -p "${SRC_DIR}/third-party-licenses"
for f in "${VPI}"/doc/LICENSE.*; do
  cp "${f}" "${SRC_DIR}/third-party-licenses/"
done

# Keep the build directory from carrying a second ~1 GB copy into any later step.
rm -rf "${DEB_ROOT}"
